package com.reviewer.Reviewer.repository;

import com.reviewer.Reviewer.models.Film.film.Film;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;

@Repository
public class InMemoryFilmDAO {
    private final List<Film> FILMS = new ArrayList<>();
//            List.of(
//            Film.builder()
//                    .filmLink("https://www.youtube.com/watch?v=qcPfI0y7wRU")
//                    .genres("Фантастика 18+")
//                    .time("2 ч 49 мин")
//                    .artists(List.of("Мэттью Макконахи", "Энн Хэтэуэй", "Джессика Честейн", "Маккензи Фой", "Майкл Кейн"))
//                    .filmMaker("Кристофер Нолан")
//                    .longDescription("В недалёком будущем, когда планета Земля охвачена экологической катастрофой, человечество стоит на грани вымирания. Пыльные бури, уничтожающие урожай, и нарастающий голод – лишь предвестники грядущего краха. Надежды практически нет, но в отчаянии рождается последняя, отчаянная надежда. \n\n Купер, в прошлом блестящий пилот и инженер, а ныне фермер, вынужденный заботиться о своих детях, неожиданно получает шанс вернуться к своей страсти – исследованию космоса. Он оказывается в эпицентре секретной миссии, призванной спасти человечество от гибели. \n\nВ этом путешествии Куперу предстоит столкнуться с невероятными явлениями, пройти через испытания, которые проверят не только его навыки, но и его веру в человечество, в его детей. Он будет разрываться между долгом перед семьей и долгом перед всей цивилизацией.\n\nЧто скрывает в себе этот таинственный космос? Какую цену придется заплатить за спасение? И сможет ли он, отважный исследователь и любящий отец, найти новый дом для человечества, прежде чем угаснет последний луч надежды?")
//                    .shortDescription("Когда засуха, пыльные бури и вымирание растений приводят человечество к продовольственному кризису, коллектив исследователей и учёных отправляется сквозь червоточину (которая предположительно соединяет области пространства-времени через большое расстояние) в путешествие, чтобы превзойти прежние ограничения для космических путешествий человека и найти планету с подходящими для человечества условиями.")
//                    .descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/430042eb-ee69-4818-aed0-a312400a26bf/600x900",
//                            "/FilmImg/Interstellar1-short.png",
//                            "/FilmImg/Interstellar2-short.png",
//                            "/FilmImg/Interstellar3-long.png"))
//                    .filmTitle("Интерстеллар")
//                    .descRating("8.7")
//                    .country("США, Великобритания, Канада")
//                    .releaseDate("2014")
//                    .build(),
//
//            Film.builder()
//                    .filmLink("https://www.youtube.com/watch?v=fYBmoH1io_E")
//                    .genres("Комедия 18+")
//                    .time("1 ч 29 мин")
//                    .artists(List.of("Сами Насери", "Фредерик Дифенталь", "Марион Котийяр", "Эмма Виклунд", "Бернар Фарси"))
//                    .filmMaker("Жерар Пирес")
//                    .longDescription("Он мечтал о скорости, но был скован улицами Марселя, развозя пиццу. Шесть лет ожидания, и вот - шанс. Даниэль Моралес, бывший доставщик, получает заветное удостоверение таксиста. Его новый Peugeot 406 - это не просто машина, это ключ к свободе, дорога к новым рекордам… и первым неприятностям. \n\n Скорость - его стихия, правила дорожного движения - лишь досадная помеха. Но эта лихая езда, граничащая с безумием, привлекает внимание. Чьё? И что скрывается за улыбкой клиентки, предложившей ему больше, чем просто чаевые? \n\n Она - Камилла Кутан-Корбадек, женщина, хранящая секрет о своем сыне, Эмильене. Кажется, он - программист, но что-то не так. Он робок, неуклюж и тайно влюблен в комиссара полиции Петру, которая видит в нём лишь объект для шуток.\nНо что произойдёт, когда судьбы Даниэля и Эмильена, двух таких разных людей, пересекутся? Что таит в себе этот таинственный город? И какую роль в этой истории сыграет погоня, о которой ещё никто не знает? Пристегните ремни. Дорога только начинается…")
//                    .shortDescription("Таксист Даниэль помешан на быстрой езде. Как ураган проносится он по извилистым улицам Марселя на мощном ревущем «Пежо», пугая прохожих и приводя в ужас пассажиров. Начинающий следователь Эмильен вынуждает его помогать в поимке банды грабителей банков, каждый раз ускользающих от полиции на неуловимых «Мерседесах».")
//                    .descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/10893610/67f3c053-f324-419d-932e-3d234f2105f5/600x900",
//                            "/FilmImg/Taxi1-short.png", "/FilmImg/Taxi2-short.png", "/FilmImg/Taxi3-long.png"))
//                    .filmTitle("Такси")
//                    .descRating("8.0")
//                    .country("Франция")
//                    .releaseDate("1998")
//                    .build(),
//
//            Film.builder()
//                    .filmLink("https://www.youtube.com/watch?v=tTwFeGArcrs")
//                    .genres("Драма 18+")
//                    .time("1 ч 52 мин")
//                    .artists(List.of("Франсуа Клюзе",
//                            "Омар Си",
//                            "Анн Ле Ни",
//                            "Одри Флёро",
//                            "Жозефин де Мо"))
//                    .filmMaker("Оливье Накаш")
//                    .longDescription("В мире, где роскошь соседствует с отчаянием, а циничный ум – с неиссякаемым жизнелюбием, рождается невероятный союз. Филипп, аристократ, потерявший все, кроме богатства и сарказма, и Дрисс, молодой выходец из трущоб, живущий одним днем, – два человека, чьи миры, казалось бы, никогда не должны были пересечься. \n\n Этот фильм – не просто история о дружбе. Это путешествие в глубины человеческой души, исследование границ между мирами, и поиск ответа на вопрос: что значит жить по-настоящему, даже когда кажется, что все потеряно? \n\n Приготовьтесь к искренней и трогательной истории, полной смеха, слез и неожиданных откровений. Фильму, который докажет вам, что даже в самых неожиданных местах можно найти не только друга, но и смысл жизни. Узнайте, как парализованный аристократ и хулиганистый парень из пригорода перевернут мир друг друга, и, возможно, ваш собственный. Но помните: то, что начинается как игра, может закончиться чем-то гораздо большим…")
//                    .shortDescription("Пострадав в результате несчастного случая, богатый аристократ Филипп нанимает в помощники человека, который менее всего подходит для этой работы, – молодого жителя предместья Дрисса, только что освободившегося из тюрьмы. Несмотря на то, что Филипп прикован к инвалидному креслу, Дриссу удается привнести в размеренную жизнь аристократа дух приключений.")
//                    .descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/10900341/caf9f155-1a19-42f1-a0f3-9c8773e9083e/600x900",
//                            "/FilmImg/1+1-1-short.png",
//                            "/FilmImg/1+1-2-short.png",
//                            "/FilmImg/1+1-3-long.png"))
//                    .filmTitle("1+1")
//                    .descRating("8.9")
//                    .country("Франция")
//                    .releaseDate("2011")
//                    .build(),
//            Film.builder()
//                    .filmLink("https://www.youtube.com/watch?v=kgAeKpAPOYk")
//                    .genres("Драма 18+")
//                    .time("2 ч 22 мин")
//                    .artists(List.of(
//                            "Тим Роббинс",
//                            "Морган Фриман",
//                            "Боб Гантон",
//                            "Уильям Сэдлер",
//                            "Клэнси Браун"
//                    ))
//                    .filmMaker("Фрэнк Дарабонт")
//                    .longDescription("Забудьте о стенах тюрьмы, представляющих лишь физическое заточение. Шоушенк - это метафора, паутина, сотканная из отчаяния, несправедливости и медленно угасающей надежды. Энди Дюфрейн, успешный банкир, обвинен в жестоком убийстве, которого он не совершал, и приговорен к двум пожизненным заключениям в самой мрачной и безнадежной тюрьме штата Мэн. Погрузитесь в мир, где коррупция – норма, жестокость – валюта, а время тянется мучительно медленно, стирая личность и волю.\n\n “Побег из Шоушенка” – это не просто история о бегстве из тюрьмы. Это глубокая притча о силе человеческого духа, о ценности дружбы и о неугасающей надежде, которая, подобно маленькому зернышку, может прорасти даже сквозь бетон. Приготовьтесь к путешествию, которое заставит вас переосмыслить границы возможного, усомниться в справедливости мира и поверить в то, что даже в самом темном месте можно найти путь к свету.")
//                    .shortDescription("Бухгалтер Энди Дюфрейн обвинён в убийстве собственной жены и её любовника. Оказавшись в тюрьме под названием Шоушенк, он сталкивается с жестокостью и беззаконием, царящими по обе стороны решётки. Каждый, кто попадает в эти стены, становится их рабом до конца жизни. Но Энди, обладающий живым умом и доброй душой, находит подход как к заключённым, так и к охранникам, добиваясь их особого к себе расположения.")
//                    .descImages(List.of(
//                            "https://avatars.mds.yandex.net/get-kinopoisk-image/1599028/0b76b2a2-d1c7-4f04-a284-80ff7bb709a4/600x900",
//                            "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/4f0f0e31-4f8d-43cf-9c95-1a4d42606ba1/3840x",
//                            "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/55d72401-ba33-4cf5-924f-822c45486261/3840x",
//                            "https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/15a79875-4799-46fd-b51b-d3a9b42cdfe3/3840x"
//                    ))
//                    .filmTitle("Побег из Шоушенка")
//                    .descRating("9.1")
//                    .country("США")
//                    .releaseDate("1994")
//                    .build(),
//
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=tTwFeGArcrs").genres("Драма 18+").time("1 ч 52 мин").artists(List.of("Франсуа Клюзе","Омар Си", "Анн Ле Ни", "Одри Флёро", "Жозефин де Мо")).filmMaker("Оливье Накаш").longDescription("Пострадав в результате несчастного случая, богатый аристократ Филипп нанимает в помощники человека, который менее всего подходит для этой работы, – молодого жителя предместья Дрисса, только что освободившегося из тюрьмы. Несмотря на то, что Филипп прикован к инвалидному креслу, Дриссу удается привнести в размеренную жизнь аристократа дух приключений.").shortDescription("Пострадав в результате несчастного случая, богатый аристократ Филипп нанимает в помощники человека, который менее всего подходит для этой работы, – молодого жителя предместья Дрисса, только что освободившегося из тюрьмы. Несмотря на то, что Филипп прикован к инвалидному креслу, Дриссу удается привнести в размеренную жизнь аристократа дух приключений.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/10900341/caf9f155-1a19-42f1-a0f3-9c8773e9083e/600x900","FilmImg/jetbrains://idea/navigate/reference?project=Reviewer&path=static%2FFilmImg%2F1%2B1-1-short.png","jetbrains://idea/navigate/reference?project=Reviewer&path=static%2FFilmImg%2F1%2B1-2-short.png", "jetbrains://idea/navigate/reference?project=Reviewer&path=static%2FFilmImg%2F1%2B1-3-long.png")).filmTitle("1+1").descRating("8.9").country("Франция").releaseDate("2011").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=qcPfI0y7wRU").genres("Фантастика 18+").time("2 ч 49 мин").artists(List.of("Мэттью Макконахи","Энн Хэтэуэй", "Джессика Честейн", "Маккензи Фой", "Майкл Кейн")).filmMaker("Кристофер Нолан").longDescription("Когда засуха, пыльные бури и вымирание растений приводят человечество к продовольственному кризису, коллектив исследователей и учёных отправляется сквозь червоточину (которая предположительно соединяет области пространства-времени через большое расстояние) в путешествие, чтобы превзойти прежние ограничения для космических путешествий человека и найти планету с подходящими для человечества условиями.").shortDescription("Когда засуха, пыльные бури и вымирание растений приводят человечество к продовольственному кризису, коллектив исследователей и учёных отправляется сквозь червоточину (которая предположительно соединяет области пространства-времени через большое расстояние) в путешествие, чтобы превзойти прежние ограничения для космических путешествий человека и найти планету с подходящими для человечества условиями.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/430042eb-ee69-4818-aed0-a312400a26bf/600x900","jetbrains://idea/navigate/reference?project=Reviewer&path=static%2FFilmImg%2FInterstellar1-short.png","jetbrains://idea/navigate/reference?project=Reviewer&path=static%2FFilmImg%2FInterstellar2-short.png", "jetbrains://idea/navigate/reference?project=Reviewer&path=static%2FFilmImg%2FInterstellar3-long.png")).filmTitle("Интерстеллар").descRating("8.7").country("США, Великобритания, Канада").releaseDate("2014").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=fYBmoH1io_E").genres("Комедия 18+").time("1 ч 29 мин").artists(List.of("Сами Насери","Фредерик Дифенталь", "Марион Котийяр", "Эмма Виклунд", "Бернар Фарси")).filmMaker("Жерар Пирес").longDescription("Таксист Даниэль помешан на быстрой езде. Как ураган проносится он по извилистым улицам Марселя на мощном ревущем «Пежо», пугая прохожих и приводя в ужас пассажиров. Начинающий следователь Эмильен вынуждает его помогать в поимке банды грабителей банков, каждый раз ускользающих от полиции на неуловимых «Мерседесах».").shortDescription("Таксист Даниэль помешан на быстрой езде. Как ураган проносится он по извилистым улицам Марселя на мощном ревущем «Пежо», пугая прохожих и приводя в ужас пассажиров. Начинающий следователь Эмильен вынуждает его помогать в поимке банды грабителей банков, каждый раз ускользающих от полиции на неуловимых «Мерседесах».").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/10893610/67f3c053-f324-419d-932e-3d234f2105f5/600x900","jetbrains://idea/navigate/reference?project=Reviewer&path=static%2FFilmImg%2FTaxi1-short.png","jetbrains://idea/navigate/reference?project=Reviewer&path=static%2FFilmImg%2FTaxi2-short.png", "jetbrains://idea/navigate/reference?project=Reviewer&path=static%2FFilmImg%2FTaxi3-long.png")).filmTitle("Такси").descRating("8.0").country("Франция").releaseDate("1998").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=kgAeKpAPOYk").genres("Драма 18+").time("2 ч 22 мин").artists(List.of("Тим Роббинс","Морган Фриман", "Боб Гантон", "Уильям Сэдлер", "Клэнси Браун")).filmMaker("Фрэнк Дарабонт").longDescription("Бухгалтер Энди Дюфрейн обвинён в убийстве собственной жены и её любовника. Оказавшись в тюрьме под названием Шоушенк, он сталкивается с жестокостью и беззаконием, царящими по обе стороны решётки. Каждый, кто попадает в эти стены, становится их рабом до конца жизни. Но Энди, обладающий живым умом и доброй душой, находит подход как к заключённым, так и к охранникам, добиваясь их особого к себе расположения.").shortDescription("Бухгалтер Энди Дюфрейн обвинён в убийстве собственной жены и её любовника. Оказавшись в тюрьме под названием Шоушенк, он сталкивается с жестокостью и беззаконием, царящими по обе стороны решётки. Каждый, кто попадает в эти стены, становится их рабом до конца жизни. Но Энди, обладающий живым умом и доброй душой, находит подход как к заключённым, так и к охранникам, добиваясь их особого к себе расположения.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/1599028/0b76b2a2-d1c7-4f04-a284-80ff7bb709a4/600x900","/FilmImg/ES1-short.png","/FilmImg/ES2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/15a79875-4799-46fd-b51b-d3a9b42cdfe3/3840x")).filmTitle("Побег из Шоушенка").descRating("9.1").country("США").releaseDate("1994").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=ar1SHxgeZUc").genres("Криминальная драма 18+").time("2 ч 55 мин").artists(List.of("Марлон Брандо","Аль Пачино", "Джеймс Каан", "Роберт Дювалл", "Ричард С. Кастеллано")).filmMaker("Фрэнсис Форд Коппола").longDescription("История семьи Корлеоне, одной из самых могущественных мафиозных кланов Америки, и ее борьбы за власть в жестоком мире организованной преступности.").shortDescription("История семьи Корлеоне, одной из самых могущественных мафиозных кланов Америки, и ее борьбы за власть в жестоком мире организованной преступности.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/10703959/ebf237d7-64a3-4b75-98f1-d228d54658e5/600x900","/FilmImg/Godfather1-short.png","/FilmImg/Godfather2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/6201401/77f89752-342a-4973-a3e3-3b2daecb074d/3840x")).filmTitle("Крестный отец").descRating("8.7").country("США").releaseDate("1972").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=HF1_epZNoCg").genres("Боевик, Драма 18+").time("2 ч 32 мин").artists(List.of("Кристиан Бэйл","Хит Леджер", "Аарон Экхарт", "Майкл Кейн", "Гари Олдман")).filmMaker("Кристофер Нолан").longDescription("Бэтмен, комиссар Гордон и Харви Дент противостоят Джокеру, анархисту и гению преступности, который пытается погрузить Готэм в хаос.").shortDescription("Бэтмен, комиссар Гордон и Харви Дент противостоят Джокеру, анархисту и гению преступности, который пытается погрузить Готэм в хаос.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/1599028/0fa5bf50-d5ad-446f-a599-b26d070c8b99/600x900","/FilmImg/Dark-Knight1-short.png","/FilmImg/Dark-Knight2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1777765/989a9e02-3dd6-4c9a-ac1f-39b44f05a227/3840x")).filmTitle("Темный рыцарь").descRating("8.5").country("США, Великобритания").releaseDate("2008").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=4r2Z0U9Y53o").genres("Историческая драма 18+").time("3 ч 15 мин").artists(List.of("Лиам Нисон","Бен Кингсли", "Рэйф Файнс", "Кэролайн Гудолл", "Эмбет Дэвидц")).filmMaker("Стивен Спилберг").longDescription("История немецкого бизнесмена Оскара Шиндлера, который спасает более тысячи польских евреев от гибели во время Холокоста.").shortDescription("История немецкого бизнесмена Оскара Шиндлера, который спасает более тысячи польских евреев от гибели во время Холокоста.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/6201401/1e1ac6d9-c658-4f5f-937e-d080bca0d893/600x900","/FilmImg/Schindler's List1-short.png","/FilmImg/Schindler's List2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/0a919184-43b0-426f-ad89-08857eb27b00/3840x")).filmTitle("Список Шиндлера").descRating("8.8").country("США").releaseDate("1993").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=otmeAaifX04").genres("Драма, Романтика").time("2 ч 22 мин").artists(List.of("Том Хэнкс","Робин Райт", "Гари Синиз", "Салли Филд", "Майкелти Уильямсон")).filmMaker("Роберт Земекис").longDescription("История жизни Форреста Гампа, человека с необычной судьбой, который становится свидетелем и участником ключевых событий американской истории.").shortDescription("История жизни Форреста Гампа, человека с необычной судьбой, который становится свидетелем и участником ключевых событий американской истории.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/1599028/3560b757-9b95-45ec-af8c-623972370f9d/600x900","/FilmImg/Forrest Gump1-short.png","/FilmImg/Forrest Gump2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/9c918339-f643-4663-a716-4655c121a674/3840x")).filmTitle("Форрест Гамп").descRating("8.8").country("США").releaseDate("1994").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=85Zz1CCXyDI").genres("Научная фантастика, Триллер 12+").time("2 ч 28 мин").artists(List.of("Леонардо ДиКаприо","Джозеф Гордон-Левитт", "Эллен Пейдж", "Том Харди", "Киллиан Мерфи")).filmMaker("Кристофер Нолан").longDescription("Дом Кобб, вор экстрасенс, получает задание совершить невозможное: не украсть идею, а внедрить ее в разум цели.").shortDescription("Дом Кобб, вор экстрасенс, получает задание совершить невозможное: не украсть идею, а внедрить ее в разум цели.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/8ab9a119-dd74-44f0-baec-0629797483d7/600x900","/FilmImg/","/FilmImg/", "https://avatars.mds.yandex.net/get-kinopoisk-image/1777765/5bc86e3a-652f-4a8f-8b4b-aeebed05e1c2/3840x")).filmTitle("Начало").descRating("8.7").country("США, Великобритания").releaseDate("2010").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=C7-7qQ61QHU").genres("Драма, Триллер 18+").time("2 ч 19 мин").artists(List.of("Эдвард Нортон","Брэд Питт", "Хелена Бонэм Картер", "Джаред Лето", "Ричмонд Аркетт")).filmMaker("Дэвид Финчер").longDescription("Человек, страдающий от бессонницы, находит спасение в бойцовском клубе, где он обретает смысл жизни и освобождение от навязанных обществом ценностей.").shortDescription("Человек, страдающий от бессонницы, находит спасение в бойцовском клубе, где он обретает смысл жизни и освобождение от навязанных обществом ценностей.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/4716873/85b585ea-410f-4d1c-aaa5-8d242756c2a4/600x900","/FilmImg/fight club1-short.png","/FilmImg/fight club2-short.png", "https://api.kinoart.ru/storage/post/928/regular_detail_picture-cfbef417cfdd8f654f3628267381a491.jpg")).filmTitle("Бойцовский клуб").descRating("8.7").country("США, Германия").releaseDate("1999").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=7ZjN5TiYzuI").genres("Фантастика, Боевик, Приключения 12+").time("2 ч 4 мин").artists(List.of("Марк Хэмилл","Харрисон Форд", "Кэрри Фишер", "Билли Ди Уильямс", "Фрэнк Оз")).filmMaker("Ирвин Кершнер").longDescription("После разрушения Звезды Смерти повстанцы продолжают бороться с Галактической Империей, а Люк Скайуокер отправляется на поиски мастера Йоды, чтобы овладеть Силой.").shortDescription("После разрушения Звезды Смерти повстанцы продолжают бороться с Галактической Империей, а Люк Скайуокер отправляется на поиски мастера Йоды, чтобы овладеть Силой.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/6201401/42f4a53f-b353-4700-bbb7-525837c46630/600x900","/FilmImg/SW5ep1-short.png","/FilmImg/SW5ep2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/0055b5cc-cee8-4a45-bce3-d9890df38882/3840x")).filmTitle("Звездные войны: Эпизод V - Империя наносит ответный удар").descRating("8.1").country("США").releaseDate("1980").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=YihPA42fdQ8").genres("Научная фантастика, Боевик 18+").time("2 ч 16 мин").artists(List.of("Киану Ривз","Лоренс Фишборн", "Кэрри-Энн Мосс", "Хьюго Уивинг", "Глория Фостер")).filmMaker("Лана Вачовски, Лилли Вачовски").longDescription("Программист Томас Андерсон узнает, что мир, в котором он живет, – это Матрица, компьютерная симуляция, и присоединяется к повстанцам, чтобы бороться за свободу.").shortDescription("Программист Томас Андерсон узнает, что мир, в котором он живет, – это Матрица, компьютерная симуляция, и присоединяется к повстанцам, чтобы бороться за свободу.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/4774061/cf1970bc-3f08-4e0e-a095-2fb57c3aa7c6/600x900","/FilmImg/matrix1-short.png","/FilmImg/matrix2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/d69ebb58-f07d-498f-8f04-71a0ed636a87/3840x")).filmTitle("Матрица").descRating("8.5").country("США, Австралия").releaseDate("1999").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=9JTNhAOVosk").genres("Триллер, Ужасы, Детектив 18+").time("1 ч 58 мин").artists(List.of("Джоди Фостер","Энтони Хопкинс", "Скотт Гленн", "Тед Левайн", "Дайан Бэйкер")).filmMaker("Джонатан Демме").longDescription("Стажерка ФБР обращается за помощью к доктору Ганнибалу Лектеру, чтобы поймать серийного убийцу Буффало Билла.").shortDescription("Стажерка ФБР обращается за помощью к доктору Ганнибалу Лектеру, чтобы поймать серийного убийцу Буффало Билла.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/6201401/9c655ce1-2b59-4941-97aa-f9e928ed0ff4/600x900","/FilmImg/SL1-short.png","/FilmImg/SL2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/86f2f7f2-16ce-4dca-8fdb-4ca21f8720e8/3840x")).filmTitle("Молчание ягнят").descRating("8.3").country("США").releaseDate("1991").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=bBU_64CTNsw").genres("Комедия, Семейный 0+").time("1 ч 43 мин").artists(List.of("Маколей Калкин","Джо Пеши", "Дэниел Стерн", "Кэтрин О’Хара", "Джон Кэнди")).filmMaker("Крис Коламбус").longDescription("Семья забывает Кевина дома в рождественской суматохе, и он должен защитить свой дом от грабителей.").shortDescription("Семья забывает Кевина дома в рождественской суматохе, и он должен защитить свой дом от грабителей.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/6201401/022a58e3-5b9b-411b-bfb3-09fedb700401/600x900","/FilmImg/home Alone1-short.png","/FilmImg/home Alone2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/1d071245-34b2-4712-b3f9-57022ada4ec2/3840x")).filmTitle("Один дома").descRating("8.3").country("США").releaseDate("1990").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=OCtt7giwbi0").genres("фантастика, Комедия, Приключения 12+").time("1 ч 56 мин").artists(List.of("Майкл Дж. Фокс","Кристофер Ллойд", "Лиа Томпсон", "Криспин Гловер", "Джордж ДиЧенцо")).filmMaker("Роберт Земекис").longDescription("Подросток Марти МакФлай отправляется в прошлое на машине времени и должен исправить ход истории, чтобы спасти свое будущее.").shortDescription("Подросток Марти МакФлай отправляется в прошлое на машине времени и должен исправить ход истории, чтобы спасти свое будущее.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/1599028/73cf2ed0-fd52-47a2-9e26-74104360786a/600x900","/FilmImg/BF1-short.png","/FilmImg/BF2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/70901cde-8233-42b2-b60a-3c0cdb4bcee8/3840x")).filmTitle("Назад в будущее").descRating("8.6").country("США").releaseDate("1985").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=I7c1etV7D7g").genres("Романтическая Драма 12+").time("3 ч 14 мин").artists(List.of("Леонардо ДиКаприо","Кейт Уинслет", "Билли Зейн", "Кэти Бейтс", "Глория Стюарт")).filmMaker("Джеймс Кэмерон").longDescription("История любви на борту Титаника между Джеком и Розой, прерванная трагической катастрофой.").shortDescription("История любви на борту Титаника между Джеком и Розой, прерванная трагической катастрофой.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/10592371/7f0e6761-4635-46ad-b804-59d5cf1ae85c/600x900","/FilmImg/titanic1-short.png","/FilmImg/titanic2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1777765/5ae974be-6e73-4ec8-b29f-249426dce2b0/3840x")).filmTitle("Титаник").descRating("8.4").country("США").releaseDate("1997").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=QqXw_fzeWjA").genres("фантастика, Боевик, Триллер 18+").time("2 ч 17 мин").artists(List.of("Арнольд Шварценеггер","Линда Хэмилтон", "Эдвард Ферлонг", "Роберт Патрик", "Джо Мортон")).filmMaker("Джеймс Кэмерон").longDescription("Терминатор Т-1000 отправляется из будущего, чтобы убить Джона Коннора, а для его защиты отправляется перепрограммированный Терминатор Т-800.").shortDescription("Терминатор Т-1000 отправляется из будущего, чтобы убить Джона Коннора, а для его защиты отправляется перепрограммированный Терминатор Т-800.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/1704946/ade65029-952f-488d-87b2-20c676970151/600x900","/FilmImg/terminator21-short.png","/FilmImg/terminator22-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/4303601/2817a3b5-7c65-4094-a78f-48994f7f3be8/3840x")).filmTitle("Терминатор 2: Судный день").descRating("8.4").country("США, Франция").releaseDate("1991").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=a-9JPXDfa_g").genres("Мультфильм, Драма, Приключения 0+").time("1 ч 28 мин").artists(List.of("Джонатан Тейлор Томас","Мэттью Бродерик", "Джеймс Эрл Джонс", "Джереми Айронс", "Чич Марин")).filmMaker("Роджер Аллерс, Роб Минкофф").longDescription("Львенок Симба, наследник трона, вынужден бежать после смерти своего отца и должен вернуться, чтобы вернуть себе законный титул.").shortDescription("Львенок Симба, наследник трона, вынужден бежать после смерти своего отца и должен вернуться, чтобы вернуть себе законный титул.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/1704946/60aa1abc-b754-4817-ad9c-0bcda427a12b/600x900","/FilmImg/lion King1-short.png","/FilmImg/lion King2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/4f6c3b73-db7c-44b7-88a9-246264416ae3/3840x")).filmTitle("Король Лев").descRating("8.8").country("США").releaseDate("1994").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=6VAbxqRaFPE").genres("Мультфильм, Фантастика, Приключения 0+").time("1 ч 38 мин").artists(List.of("Бен Бертт","Элисса Найт", "Джефф Гарлин", "Фред Уиллард", "Сигурни Уивер")).filmMaker("Эндрю Стэнтон").longDescription("Робот ВАЛЛ-И, оставшийся на загрязненной Земле, влюбляется в робота Еву, прибывшего с космического корабля.").shortDescription("Робот ВАЛЛ-И, оставшийся на загрязненной Земле, влюбляется в робота Еву, прибывшего с космического корабля.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/146b1b20-347b-4b6a-98c8-fdc2c75495cb/600x900","/FilmImg/WALL·E1-short.png","/FilmImg/WALL·E2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/d7433bc0-a620-41a0-9f70-0b144206f3d0/3840x")).filmTitle("ВАЛЛ-И").descRating("8.5").country("США").releaseDate("2008").build(),
//                    Film.builder().filmLink("https://www.youtube.com/watch?v=TODt_q-_4C4").genres("Фэнтези, Драма 18+").time("3 ч 9 мин").artists(List.of("Том Хэнкс","Майкл Кларк Дункан", "Дэвид Морс", "Бонни Хант", "Даг Хатчисон")).filmMaker("Фрэнк Дарабонт").longDescription("Начальник блока смертников знакомится с заключенным, обладающим даром исцеления, и его жизнь навсегда меняется.").shortDescription("Начальник блока смертников знакомится с заключенным, обладающим даром исцеления, и его жизнь навсегда меняется.").descImages(List.of("https://avatars.mds.yandex.net/get-kinopoisk-image/1599028/4057c4b8-8208-4a04-b169-26b0661453e3/600x900","/FilmImg/green Mile1-short.png","/FilmImg/green Mile2-short.png", "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/c6f19e6f-79dc-43de-80cc-11d8b31fac34/3840x")).filmTitle("Зеленая миля").descRating("9.1").country("США").releaseDate("1999").build()
//                    );

    public List<Film> findAllFilms() {
        return FILMS;
    }

    public Film findFilmByFilmName(String filmName) {
        return FILMS.stream()
                .filter(element -> element.getFilmTitle().equals(filmName))
                .findFirst()
                .orElse(null);
    }
}
